Models/ErrorViewModel.cs
namespace AspNet_MVC_Mongo_Sample.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SampleModel1.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.Text.Json.Serialization;

namespace AspNet_MVC_Mongo_Sample.Models
{
    public class SampleModel1
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string? Id { get; set; }

        [BsonElement("version")]
        public int Version { get; set; } = 1;

        [BsonElement("level")]
        public string Level { get; set; } = null!;

        public string Statement { get; set; } = null!;

        public SampleModel1(string? id, int version, string level, string statement)
        {
            Id = id;
            Version = version;
            Level = level;
            Statement = statement;
        }

        public SampleModel1()
        {
        }

        [BsonElement("Goals")]
        public List<SampleModel5> Goals { get; set; } = null!;       

 
    }
}

Models/SampleModel2.cs
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace AspNet_MVC_Mongo_Sample.Models
{
    public class SampleModel2
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string? Id { get; set; }

        public string SampleModel1_Id { get; set; } = null!;

        [BsonElement("type")]
        public string Type { get; set; } = null!;

        [BsonElement("level")]
        public string Level { get; set; } = null!;
        
        public SampleModel3 Business_Case { get; set; } = null!;

        public string Status { get; set; } = null!;
    }
}

Models/SampleModel3.cs
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;
using System.Diagnostics.CodeAnalysis;
using System.ComponentModel;

namespace AspNet_MVC_Mongo_Sample.Models
{
    public class SampleModel3
    {
        public string ProblemStatement { get; set; } = null!;

        public string EconomicAnalysis { get; set; } = null!;

        public string SolutionOptions { get; set; } = null!;

        public string ImplementationApproach { get; set; } = null!;

        public string Status { get; set; } = null!;

    }
}

Models/SampleModel4.cs
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;
using System.Diagnostics.CodeAnalysis;

namespace AspNet_MVC_Mongo_Sample.Models
{
    public class Strategy
    {
        [BsonElement("strategy_id")]
        public int strategy_id { get; set; }

        [BsonElement("description")]
        public string Description { get; set; } = null!;

        [BsonElement("status")]
        public string status { get; set; } = null!;
    }
}

Models/SampleModel5.cs
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;
using System.Diagnostics.CodeAnalysis;
using System.ComponentModel;

namespace AspNet_MVC_Mongo_Sample.Models
{
    public class SampleModel5
    {
        [BsonElement("goal_id")]
        public int goal_id { get; set; }

        [BsonElement("description")]
        public string Description { get; set; } = null!;

        [BsonElement("objectives")]
        public List<SampleModel6> objectives { get; set; } = null!;


    }
}

Models/SampleModel6.cs
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace AspNet_MVC_Mongo_Sample.Models
{
    public class SampleModel6
    {
        [BsonElement("objective_id")]
        public int objective_id { get; set; }

        [BsonElement("description")]
        public string Description { get; set; } = null!;

        [BsonElement("type")]
        public string type { get; set; } = null!;

        [BsonElement("definition")]
        public string definition { get; set; } = null!;

        [BsonElement("strategies")]
        public List<Strategy> stratgies { get; set; } = null!;
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using AspNet_MVC_Mongo_Sample.Models;

namespace AspNet_MVC_Mongo_Sample.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult SampleModel1()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SampleModel1Controller.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using AspNet_MVC_Mongo_Sample.Models;
using AspNet_MVC_Mongo_Sample.Services;
using System.Diagnostics;

namespace AspNet_MVC_Mongo_Sample.Controllers
{
    /*
    [ApiController]
    [Route("api/[controller]")]
    */
    public class SampleModel1Controller : Controller
    {
        private readonly SampleModel1Svc _model1Service;
        public SampleModel1Controller(SampleModel1Svc model1Service)
        {
            _model1Service = model1Service;
        }
        public IActionResult SampleModel1()
        {
            List<SampleModel1> sampleModel1List = _model1Service.GetAll();
            return View(sampleModel1List);
        }

        public IActionResult AddSampleModel1(SampleModel1 sampleModel1)
        {
            _model1Service.AddSampleModel1(sampleModel1);
            Debug.Write("after tranaction..");
            return Redirect("SampleModel1");
        }

        public IActionResult CreateSampleModel1Form()
        {
            ViewData["Action"] = "Create";
            SampleModel1 emptyModel = new SampleModel1();
            return View(emptyModel);
        }

    }
}

Controllers/SampleModel2Controller.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using AspNet_MVC_Mongo_Sample.Models;
using AspNet_MVC_Mongo_Sample.Services;
using System.Diagnostics;

namespace AspNet_MVC_Mongo_Sample.Controllers
{
    /*[ApiController]
    [Route("api/[controller]")]*/
    public class SampleModel2Controller : Controller
    {
        private readonly SampleModel2Svc _model2Service;

        public SampleModel2Controller(SampleModel2Svc model2Service)
        {
            _model2Service = model2Service;
        }

        public IActionResult SampleModel2()
        {
            List<SampleModel2> sampleModel2List = _model2Service.GetProposalList();
            return View(sampleModel2List);
        }

        public IActionResult Add(SampleModel2 sampleModel2)
        {
            _model2Service.Add(sampleModel2);
            Debug.Write("after tranaction..");
            return Redirect("Proposal");
        }

        public IActionResult CreateSampleModel2Form()
        {
            ViewData["Action"] = "Create";
            SampleModel2 emptyModel = new SampleModel2();
            return View(emptyModel);
        }


    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/SampleModel1/CreateSampleModel1Form.cshtml
@model AspNet_MVC_Mongo_Sample.Models.SampleModel1

@{
    ViewData["Title"] = "Create SampleModel1";
    
}

<div id="CreateSampleModel1TableContainer">
    <h4>Create SampleModel1 and associated goals, objectives & strategies</h4>
    <p></p>
    @if (ViewData["Action"].Equals("Create"))
    {
        <fieldset>
            @using (Html.BeginForm("AddSampleModel1", "SampleModel1"))
            {
                <div class="editor-label">
                    @Html.LabelFor(model => model.Statement)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Statement)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Level)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Level)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Goals[0].Description, "Goal Description")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Goals[0].Description)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Goals[0].objectives[0].Description, "Objective Description")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Goals[0].objectives[0].Description)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Goals[0].objectives[0].type, "Objective Type")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Goals[0].objectives[0].type)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Goals[0].objectives[0].stratgies[0].Description, "Strategy Description")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Goals[0].objectives[0].stratgies[0].Description)
                </div>

                <button>AddSampleModel1</button>
            }
        </fieldset>
    }
</div>


@section scripts {
    <script type="text/javascript">

    </script>
}

Views/SampleModel1/SampleModel1.cshtml
@model IEnumerable<AspNet_MVC_Mongo_Sample.Models.SampleModel1>

@{
    ViewData["Title"] = "SampleModel1 Page";
    
}

<div id="LoadSampleModel1TableContainer">
    <h4>Manage SampleModel1(s) and Associated Goals, Objectives and Strategies</h4>
    <hr />
    <p>
        <a asp-action="CreateSampleModel1Form">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Version)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Level)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Goals)
                </th>
                 <th></th>
            </tr>
        </thead>        
    @foreach(var item in Model)
    {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Version)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Level)
                </td>
                <td>
                    <b>Goal:</b>
                @if (item.Goals is not null){
                @foreach (var g in item.Goals)
                {
                @Html.DisplayFor(modelItem => g.Description)
                <p></p>        
                <b>Objectives:</b>
                            <p></p>
                            @if (g.objectives is not null)
                        {
                        @foreach (var obje in g.objectives)
                        {
                                    string paramValue = obje.type + ":" + obje.Description;
                                    @Html.DisplayFor(modelItem => paramValue)
                                    <p></p>
                                    <b>Strategies:</b>
                                    <p></p>
                                    @if (obje.stratgies is not null){
                            @foreach (var strat in obje.stratgies)
                            {
                                            string paramValue1 = strat.Description + ":" + strat.status;
                                            @Html.DisplayFor(modelItem => paramValue1)
                                <p></p>
                            }
                                    }
                        }
                        }
                
                }
                }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>           
   
    }
    </table>
</div>

@section scripts {
    <script type="text/javascript">

    </script>
}

Views/SampleModel2/CreateSampleModel2Form.cshtml
@model AspNet_MVC_Mongo_Sample.Models.SampleModel2

@{
    ViewData["Title"] = "Create SampleModel2";
    
}

<div id="CreateSampleModel2TableContainer">
    <h4>Create a SampleModel2</h4>
    <p></p>
    @if (ViewData["Action"].Equals("Create"))
    {
        <fieldset>
            @using (Html.BeginForm("Add", "SampleModel2"))
            {
                <div class="editor-label">
                    @Html.LabelFor(model => model.Type)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Type)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Level)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Level)
                </div>
                <div title="Enter Business Case Details"></div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.Business_Case.ProblemStatement, "Problem Statement/Strategic Context")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Business_Case.ProblemStatement)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Business_Case.EconomicAnalysis, "Economic Analysis")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Business_Case.EconomicAnalysis)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Business_Case.SolutionOptions, "Solution Options")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Business_Case.SolutionOptions)
                </div>

                
                <button>AddProposal</button>
            }
        </fieldset>
    }
</div>


@section scripts {
    <script type="text/javascript">

    </script>
}

Views/SampleModel2/SampleModel2.cshtml
@model IEnumerable<AspNet_MVC_Mongo_Sample.Models.SampleModel2>

@{
    ViewData["Title"] = "SampleModel2 Page";

}

<div id="SampleModel2TableContainer">
    <h4>Manage Proposals of any Type (ex: Idea, Change, New Initiative, Digital Transformation, etc.)</h4>
    <hr />
    <p>
        <a asp-action="CreateSampleModel2lForm">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SampleModel1_Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Level)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Business_Case)
                </th>
                 <th></th>
            </tr>
        </thead>        
    @foreach(var item in Model)
    {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>                    
                    @Html.ActionLink(item.SampleModel1_Id, "SampleModel1", "SampleModel1")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Level)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @{
                        string p0 = "Problem Statement: " + @item.Business_Case.ProblemStatement;
                        @Html.DisplayFor(modelItem => p0)
                        <p></p>
                        string p1 = "Economic Analysis: " + @item.Business_Case.EconomicAnalysis;
                        @Html.DisplayFor(modelItem => p1)
                        <p></p>
                        string p3 = "Solution Options: " + @item.Business_Case.SolutionOptions;
                        @Html.DisplayFor(modelItem => p3)
                        <p></p>
                    }                  
                                        
                    
                </td>
                <td>
                
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>           
   
    }
    </table>
</div>

@section scripts {
    <script type="text/javascript">

    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNet_MVC_Mongo_Sample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNet_MVC_Mongo_Sample.styles.css" asp-append-version="true" />
    <link href="~/css/Site.css" rel="stylesheet" type="text/css" />

    <!--<script src="~/lib/jquery/dist/jquery.min.js"></script>-->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    

    <!-- Include one of jTable styles. -->
    <link href="~/lib/jtable/themes/metro/blue/jtable.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/jtable/jquery-ui.css" rel=”stylesheet”>

    <!-- Include jTable script file. -->
    <script src="~/lib/jtable/jquery-3.7.1.min.js" type="text/javascript"></script>
    <script src="~/lib/jtable/jquery-ui-1.14.1.min.js" type="text/javascript"></script>
    <script src="~/lib/jtable/jquery.jtable.min.js" type="text/javascript"></script>

    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNet_MVC_Mongo_Sample</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SampleModel1" asp-action="SampleModel1">SampleModel1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SampleModel2" asp-action="SampleModel2">SampleModel2</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AspNet_MVC_Mongo_Sample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
</body>
</html>